#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

dbname="site"
mysqlUser="root"
mysqlPassword="blank"

mysqlCmd="mysql -u $mysqlUser -p$mysqlPassword -B -N"

$mysqlCmd -e "CREATE DATABASE IF NOT EXISTS $dbname"
# this creates the user if it does not exist:
$mysqlCmd -e "GRANT ALL PRIVILEGES ON $dbname.* TO 'wp'@'localhost' IDENTIFIED BY 'wp'"

# cd "${DIR}/../wordpress"

# wp core config --dbname=$dbname --dbuser=wp --dbpass=wp --extra-php <<PHP
# define( "WP_DEBUG", true );
# define( "WP_DEBUG_LOG", true );
# PHP

# wp core install --url=wp.dev --quiet --title="wp.dev site" --admin_name=admin --admin_email="admin@wp.dev" --admin_password="123"
